# Generated by Django 4.0.4 on 2022-04-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.IntegerField()),
                ('data_de_nascimento', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('contato', models.CharField(max_length=30)),
            ],
        ),
    ]
