# Generated by Django 4.0.4 on 2022-04-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_motos_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motos',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
